### ISSUE TITLE
``using QuantEcon`` failing on v0.4

### ISSUE THREAD

**Issue by ZacCranko** [QuantEcon/QuantEcon.jl#64]
Anyone know why this is happening with the master branch on v0.4?

```
julia> using QuantEcon
WARNING: requiring "Distributions" did not define a corresponding module.
WARNING: requiring "Distributions" did not define a corresponding module.
WARNING: requiring "Distributions" did not define a corresponding module.
WARNING: module Util should explicitly import * from Base
WARNING: module Filters should explicitly import * from Base
WARNING: requiring "Distributions" did not define a corresponding module.
WARNING: requiring "Distributions" did not define a corresponding module.
ERROR: LoadError: LoadError: UndefVarError: MultivariateNormal not defined
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
while loading /Users/zaccranko/.julia/v0.4/QuantEcon/src/lss.jl, in expression starting on line 41
while loading /Users/zaccranko/.julia/v0.4/QuantEcon/src/QuantEcon.jl, in expression starting on line 120
```

**Comment by spencerlyon2** [comment]
Will you give me the output of versioninfo()

**Comment by ZacCranko** [comment]
```
julia> versioninfo()
Julia Version 0.4.0-dev+6642
Commit 58dc82f* (2015-08-11 23:19 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY HASWELL)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by spencerlyon2** [comment]
I haven't tried on today's master. 

Can you load distributions by itself?

**Comment by ZacCranko** [comment]
I did try that, `Distributions` loads without complaint

**Comment by spencerlyon2** [comment]
Hmm. 

Have you by chance tried using Base.compile with these packages?

If so maybe try deleting the cache files...

**Comment by ZacCranko** [comment]
I haven't, this is a completely clean build of Julia that i haven't messed with. Is Travis building v0.4?

**Comment by spencerlyon2** [comment]
I don't think we've pushed to master recently enough. Usually nightly builds are a little behind anyway. 

That's is quite strange. I guess you could try the nuclear option and delete your whole package directory... I don't have great advice for this thing

**Comment by ZacCranko** [comment]
Okay so just did `rm -rf ~/.julia/v0.4` then `Pkg.add("QuantEcon")`, bad news still getting the same issue

```
julia> using QuantEcon
WARNING: requiring "Distributions" did not define a corresponding module.
WARNING: requiring "Distributions" did not define a corresponding module.
WARNING: requiring "Distributions" did not define a corresponding module.
WARNING: module Util should explicitly import * from Base
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/Polynomials.ji for module Polynomials.
WARNING: module Filters should explicitly import * from Base
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/Docile.ji for module Docile.
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/LightGraphs.ji for module LightGraphs.
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/GZip.ji for module GZip.
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/StatsBase.ji for module StatsBase.
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/ArrayViews.ji for module ArrayViews.
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/StatsFuns.ji for module StatsFuns.
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/LightXML.ji for module LightXML.
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/ParserCombinator.ji for module ParserCombinator.
INFO: Recompiling stale cache file /Users/zaccranko/.julia/lib/v0.4/AutoHashEquals.ji for module AutoHashEquals.
WARNING: requiring "Distributions" did not define a corresponding module.
WARNING: requiring "Distributions" did not define a corresponding module.
ERROR: LoadError: LoadError: UndefVarError: MultivariateNormal not defined
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
while loading /Users/zaccranko/.julia/v0.4/QuantEcon/src/lss.jl, in expression starting on line 41
while loading /Users/zaccranko/.julia/v0.4/QuantEcon/src/QuantEcon.jl, in expression starting on line 120

```

**Comment by spencerlyon2** [comment]
Hmm not sure. 

I tried scanning the commit log for Julia for today and didn't notice anything that would explain this.

Unfortunately I need my Julia to be fully working to do my research so I can't really  hop on the latest master to debug with you. 

I suppose I could do it within a docker container or something, do you reckon it's woth it?

**Comment by ZacCranko** [comment]
I was able to reproduce it with the binary off julialang.org: https://status.julialang.org/download/osx10.7+ 
so you could grab that and see if its happening for you.

**Comment by spencerlyon2** [comment]
Yep. I'll try pretty soon. 

We haven't pushed to master to register a build on Travis so I'm not sure

**Comment by spencerlyon2** [comment]
I did have the same problems with the binary.

Doing 

```
rm -rf ~/.julia/lib
```

Then


```
julia> Base.compilecache(:Distributions)
"/Users/sglyon/.julia/lib/v0.4/Distributions.ji"

julia> Base.compilecache(:QuantEcon)
```

fixed it for me.

I did have to move to the master version of Docile.jl and I was already on the master of distributions (not sure if being on Distributions master is necessary).

**Comment by ZacCranko** [comment]
What was the problem?

**Comment by spencerlyon2** [comment]
not sure... 

Somehow forcing a cached version of Distributions and allowing using QuantEcon to call that instead of load at "`using`-time" made it work.

Can you verify that it fixes your issue?

**Comment by ZacCranko** [comment]
Okay fixed. So ``rm -rf ~/.julia/lib `` followed by  ``Base.compilecache(:Distributions)`` did the trick.  ``Base.compilecache(:QuantEcon)`` was not necessary. It's slightly concerning that this is necessary, I bet it's `Distributions.jl`'s falt.

**Comment by spencerlyon2** [comment]
Not sure... Just sounds like life on the bleeding edge to me

**Comment by vtjnash** [comment]
This is https://github.com/JuliaLang/julia/issues/12586

**Comment by tkelman** [comment]
slash 9079 slash 4600... we need to fix that
